[theme]
base = "light"
primaryColor = "#1E5FA8"
backgroundColor = "#F3F5F6"
secondaryBackgroundColor = "#E4E9EC"
textColor = "#1D2B36"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
